### ISSUE TITLE
Crash when using constants in arithmetic operations

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#176] opened 2024-05-09 18:00 UTC
Using constants in arithmetic leads to crashes in Charon.

See these changes for reproducers.
https://github.com/cryspen/libcrux/commit/5b23caf30914d9e71bb8cc29b15f1a355d4784f9

```
thread 'rustc' panicked at 'libcrux_traits does not have a "explicit_predicates_of"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:205:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: Thread panicked when extracting body.
  --> libcrux-ml-kem/src/polynomial.rs:16:1
   |
16 | pub(crate) const VECTORS_IN_RING_ELEMENT: usize =
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: Thread panicked when extracting body.
  --> libcrux-ml-kem/src/invert_ntt.rs:71:1
   |
71 | / pub(crate) fn invert_ntt_at_layer_4_plus<Vector: Operations>(
72 | |     zeta_i: &mut usize,
73 | |     mut re: PolynomialRingElement<Vector>,
74 | |     layer: usize,
75 | | ) -> PolynomialRingElement<Vector> {
   | |__________________________________^

warning: Thread panicked when extracting body.
  --> libcrux-ml-kem/src/ntt.rs:75:1
   |
75 | / pub(crate) fn ntt_at_layer_4_plus<Vector: Operations>(
76 | |     zeta_i: &mut usize,
77 | |     mut re: PolynomialRingElement<Vector>,
78 | |     layer: usize,
79 | |     _initial_coefficient_bound: usize,
80 | | ) -> PolynomialRingElement<Vector> {
   | |__________________________________^

warning: Thread panicked when extracting body.
  --> libcrux-ml-kem/src/polynomial.rs:34:5
   |
34 |     pub(crate) fn from_i16_array(a: [i16; 256]) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ```

This may be the same as #175

**Comment by Nadrieril** [comment] 2024-05-09 18:05
Pretty sure we fixed that in https://github.com/AeneasVerif/charon/pull/173. Please confirm this is still an issue with Charon main when you can

**Comment by Nadrieril** [comment] 2024-05-09 19:54
Ah, seeing the error messages this looks like a different thing. I'll investigate on Monday

**Comment by Nadrieril** [comment] 2024-05-14 09:17
confirmed that this is duplicate of https://github.com/AeneasVerif/charon/issues/175. I've got a fix on the way. Closing.

**Closed by Nadrieril** 2024-05-14 09:17 UTC
