### ISSUE TITLE
Add support for quantified lifetimes (`for <'a>`)

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#79] opened 2024-03-01 17:31 UTC
For now Charon does not support quantified lifetimes, as indicated by `for <'a> ...` in the where clauses.

**Comment by Nadrieril** [comment] 2024-04-08 10:05
Duplicate of https://github.com/AeneasVerif/charon/issues/67

**Closed** 2024-05-14 13:19 UTC
Labels: A-lifetimes, C-unsupported-language-feature
